spring:
  application:
    name: auth
  datasource:
    url: jdbc:mariadb://localhost:3306/match_auth
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true